import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "./login.module.scss";

import { Link, Button, TextField, HorizontalLine } from "components";

import { CreateProfileMethods } from "./modules";
import { SubmitHandler, useForm } from "react-hook-form";
import { Ilogin, IcreateProfile } from "./modules/create-profile.types";

const CreateProfile = () => {
  const {
    loadingCreateProfileButton,
    setLoadingCreateProfileButton,
    submitCreateProfile,
    userId,
  } = CreateProfileMethods();

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<IcreateProfile>({
    mode: "onSubmit",
  });

  const onSubmitCreateProfile: SubmitHandler<IcreateProfile> = (data) => {
    submitCreateProfile(data);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen flex">
        {/* First half  */}
        <div className="hidden sm:hidden md:hidden lg:flex w-full lg:w-3/5 justify-around items-center bg-cover bg-[url('https://images.unsplash.com/photo-1650825556125-060e52d40bd0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80')]"></div>
        {/* Second Half  */}
        <div className="flex w-full lg:w-2/5 flex-col">
          <div className="flex justify-center flex-grow items-center bg-white space-y-8 font-sans">
            <div className="w-full px-5 sm:px-20 md:px-16 lg:px-8 xl:px-10">
              <div className="flex  w-full p-5 flex-col ">
                <div className="flex justify-center identifier__icon w-full ">
                  <Image
                    src="/vercel.svg"
                    alt="icon"
                    width={74}
                    height={74}
                    className="identifier__icon--src"
                  />
                </div>
                <div className="flex text-base identifier__info justify-center font-normal text-gray-600 mt-7 mb-6">
                  You doesn&#39;t seem to be registered with us. Create a new
                  account.
                </div>
              </div>

              <form
                className="bg-white rounded-md"
                onSubmit={handleSubmit(onSubmitCreateProfile)}
              >
                <div className="flex items-center mb-8 w-full">
                  <TextField
                    id="fullName"
                    type="text"
                    placeholder="e.g. Ruhi Verma"
                    label="Full Name"
                    {...register("fullName")}
                  />
                </div>
                <div className="flex items-center mb-8 w-full">
                  <TextField
                    id="password"
                    type="password"
                    placeholder="min. 6 characters"
                    label="Password"
                    {...register("password")}
                  />
                </div>
                <div className="flex items-center mb-8 w-full">
                  <TextField
                    id="userId"
                    type="text"
                    isHidden={true}
                    {...register("userId")}
                  />
                </div>

                <Button
                  type="submit"
                  isFullWidth={true}
                  state="primary"
                  classNames="py-3"
                  isLoading={loadingCreateProfileButton}
                >
                  Sign Up
                </Button>
                <div className="identifier__info text-xs font-normal leading-5 mt-2 text-neutral">
                  By proceeding, you agree to our
                  <Link href="/"> Terms of Services </Link> and
                  <Link href="/"> Privacy Policy </Link>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

// CreateProfile.isProtectedPage = true;
export default CreateProfile;
